import requests

from django.core.management.base import BaseCommand
from football.models import Team, DefensivePoints
# from time import sleep


class Command(BaseCommand):

    def handle(self, *args, **kwargs):



        team = Team.objects.get(short_name='Patriots')	
        def_points = DefensivePoints(team=team, year=2022, points=173)	
        def_points.save()

        team = Team.objects.get(short_name='Eagles')	
        def_points = DefensivePoints(team=team, year=2022, points=158)	
        def_points.save()
        team = Team.objects.get(short_name='49ers')	
        def_points = DefensivePoints(team=team, year=2022, points=156)	
        def_points.save()
        team = Team.objects.get(short_name='Cowboys')	
        def_points = DefensivePoints(team=team, year=2022, points=153)	
        def_points.save()
        team = Team.objects.get(short_name='Bills')	
        def_points = DefensivePoints(team=team, year=2022, points=138)	
        def_points.save()
        team = Team.objects.get(short_name='Ravens')	
        def_points = DefensivePoints(team=team, year=2022, points=129)	
        def_points.save()
        team = Team.objects.get(short_name='Jets')	
        def_points = DefensivePoints(team=team, year=2022, points=122)	
        def_points.save()
        team = Team.objects.get(short_name='Commanders')	
        def_points = DefensivePoints(team=team, year=2022, points=120)	
        def_points.save()
        team = Team.objects.get(short_name='Chiefs')	
        def_points = DefensivePoints(team=team, year=2022, points=115)	
        def_points.save()
        team = Team.objects.get(short_name='Jaguars')	
        def_points = DefensivePoints(team=team, year=2022, points=111)	
        def_points.save()
        team = Team.objects.get(short_name='Colts')	
        def_points = DefensivePoints(team=team, year=2022, points=106)	
        def_points.save()
        team = Team.objects.get(short_name='Saints')	
        def_points = DefensivePoints(team=team, year=2022, points=105)	
        def_points.save()
        team = Team.objects.get(short_name='Packers')	
        def_points = DefensivePoints(team=team, year=2022, points=105)	
        def_points.save()
        team = Team.objects.get(short_name='Browns')	
        def_points = DefensivePoints(team=team, year=2022, points=102)	
        def_points.save()
        team = Team.objects.get(short_name='Broncos')	
        def_points = DefensivePoints(team=team, year=2022, points=102)	
        def_points.save()
        team = Team.objects.get(short_name='Bengals')	
        def_points = DefensivePoints(team=team, year=2022, points=100)	
        def_points.save()
        team = Team.objects.get(short_name='Seahawks')	
        def_points = DefensivePoints(team=team, year=2022, points=98)	
        def_points.save()
        team = Team.objects.get(short_name='Steelers')	
        def_points = DefensivePoints(team=team, year=2022, points=97)	
        def_points.save()
        team = Team.objects.get(short_name='Buccaneers')	
        def_points = DefensivePoints(team=team, year=2022, points=97)	
        def_points.save()
        team = Team.objects.get(short_name='Panthers')	
        def_points = DefensivePoints(team=team, year=2022, points=94)	
        def_points.save()
        team = Team.objects.get(short_name='Cardinals')	
        def_points = DefensivePoints(team=team, year=2022, points=91)	
        def_points.save()
        team = Team.objects.get(short_name='Dolphins')	
        def_points = DefensivePoints(team=team, year=2022, points=89)	
        def_points.save()
        team = Team.objects.get(short_name='Rams')	
        def_points = DefensivePoints(team=team, year=2022, points=89)	
        def_points.save()
        team = Team.objects.get(short_name='Chargers')	
        def_points = DefensivePoints(team=team, year=2022, points=87)	
        def_points.save()
        team = Team.objects.get(short_name='Giants')	
        def_points = DefensivePoints(team=team, year=2022, points=84)	
        def_points.save()
        team = Team.objects.get(short_name='Titans')	
        def_points = DefensivePoints(team=team, year=2022, points=80)	
        def_points.save()
        team = Team.objects.get(short_name='Texans')	
        def_points = DefensivePoints(team=team, year=2022, points=78)	
        def_points.save()
        team = Team.objects.get(short_name='Vikings')	
        def_points = DefensivePoints(team=team, year=2022, points=71)	
        def_points.save()
        team = Team.objects.get(short_name='Falcons')	
        def_points = DefensivePoints(team=team, year=2022, points=69)	
        def_points.save()
        team = Team.objects.get(short_name='Lions')	
        def_points = DefensivePoints(team=team, year=2022, points=64)	
        def_points.save()
        team = Team.objects.get(short_name='Raiders')	
        def_points = DefensivePoints(team=team, year=2022, points=55)	
        def_points.save()
        team = Team.objects.get(short_name='Bears')	
        def_points = DefensivePoints(team=team, year=2022, points=32)	
        def_points.save()