# Generated by Django 4.1.5 on 2023-08-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "player",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16)),
                ("full_name", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "position",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "sport",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("short_name", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "team",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TeamOffense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("games_played", models.SmallIntegerField()),
                ("points", models.SmallIntegerField()),
                ("total_yards", models.SmallIntegerField()),
                ("plays_offense", models.SmallIntegerField()),
                ("yds_per_play_offense", models.FloatField()),
                ("turnovers", models.SmallIntegerField()),
                ("fumbles_lost", models.SmallIntegerField()),
                ("first_down", models.SmallIntegerField()),
                ("pass_cmp", models.SmallIntegerField()),
                ("pass_att", models.SmallIntegerField()),
                ("pass_yds", models.SmallIntegerField()),
                ("pass_td", models.SmallIntegerField()),
                ("pass_int", models.SmallIntegerField()),
                ("pass_net_yds_per_att", models.FloatField()),
                ("pass_fd", models.SmallIntegerField()),
                ("rush_att", models.SmallIntegerField()),
                ("rush_yds", models.SmallIntegerField()),
                ("rush_td", models.SmallIntegerField()),
                ("rush_yds_per_att", models.FloatField()),
                ("rush_fd", models.SmallIntegerField()),
                ("penalties", models.SmallIntegerField()),
                ("penalties_yds", models.SmallIntegerField()),
                ("pen_fd", models.SmallIntegerField()),
                ("score_pct", models.FloatField()),
                ("turnover_pct", models.FloatField()),
                ("exp_pts_tot", models.FloatField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_offense",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TeamDefense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("games_played", models.SmallIntegerField()),
                ("points", models.SmallIntegerField()),
                ("total_yards", models.SmallIntegerField()),
                ("plays_offense", models.SmallIntegerField()),
                ("yds_per_play_offense", models.FloatField()),
                ("turnovers", models.SmallIntegerField()),
                ("fumbles_lost", models.SmallIntegerField()),
                ("first_down", models.SmallIntegerField()),
                ("pass_cmp", models.SmallIntegerField()),
                ("pass_att", models.SmallIntegerField()),
                ("pass_yds", models.SmallIntegerField()),
                ("pass_td", models.SmallIntegerField()),
                ("pass_int", models.SmallIntegerField()),
                ("pass_net_yds_per_att", models.FloatField()),
                ("pass_fd", models.SmallIntegerField()),
                ("rush_att", models.SmallIntegerField()),
                ("rush_yds", models.SmallIntegerField()),
                ("rush_td", models.SmallIntegerField()),
                ("rush_yds_per_att", models.FloatField()),
                ("rush_fd", models.SmallIntegerField()),
                ("penalties", models.SmallIntegerField()),
                ("penalties_yds", models.SmallIntegerField()),
                ("pen_fd", models.SmallIntegerField()),
                ("score_pct", models.FloatField()),
                ("turnover_pct", models.FloatField()),
                ("exp_pts_def_tot", models.FloatField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_defense",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerRushing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("age", models.SmallIntegerField()),
                ("pos", models.CharField(default=None, max_length=16)),
                ("g", models.SmallIntegerField()),
                ("gs", models.SmallIntegerField()),
                ("rush_att", models.SmallIntegerField()),
                ("rush_yds", models.SmallIntegerField()),
                ("rush_td", models.SmallIntegerField()),
                ("rush_first_down", models.SmallIntegerField()),
                ("rush_long", models.SmallIntegerField()),
                ("rush_yds_per_att", models.FloatField()),
                ("rush_yds_per_g", models.FloatField()),
                ("fumbles", models.SmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_rushing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerReturning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("age", models.SmallIntegerField()),
                ("pos", models.CharField(default=None, max_length=16)),
                ("g", models.SmallIntegerField()),
                ("gs", models.SmallIntegerField()),
                ("punt_ret", models.SmallIntegerField()),
                ("punt_ret_yds", models.SmallIntegerField()),
                ("punt_ret_td", models.SmallIntegerField()),
                ("punt_ret_long", models.SmallIntegerField()),
                ("punt_ret_yds_per_ret", models.FloatField()),
                ("kick_ret", models.SmallIntegerField()),
                ("kick_ret_yds", models.SmallIntegerField()),
                ("kick_ret_td", models.SmallIntegerField()),
                ("kick_ret_long", models.SmallIntegerField()),
                ("kick_ret_yds_per_ret", models.FloatField()),
                ("all_purpose_yds", models.SmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_returning",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerReceiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("age", models.SmallIntegerField()),
                ("pos", models.CharField(default=None, max_length=16)),
                ("g", models.SmallIntegerField()),
                ("gs", models.SmallIntegerField()),
                ("targets", models.SmallIntegerField()),
                ("rec", models.SmallIntegerField()),
                ("catch_pct", models.FloatField()),
                ("rec_yds", models.SmallIntegerField()),
                ("rec_yds_per_rec", models.FloatField()),
                ("rec_td", models.SmallIntegerField()),
                ("rec_first_down", models.SmallIntegerField()),
                ("rec_long", models.SmallIntegerField()),
                ("rec_yds_per_tgt", models.FloatField()),
                ("rec_per_g", models.FloatField()),
                ("rec_yds_per_g", models.FloatField()),
                ("fumbles", models.SmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_receiving",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerPassing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("age", models.SmallIntegerField()),
                ("pos", models.CharField(default=None, max_length=16)),
                ("g", models.SmallIntegerField()),
                ("gs", models.SmallIntegerField()),
                ("qb_rec", models.CharField(default=None, max_length=32)),
                ("pass_cmp", models.SmallIntegerField()),
                ("pass_att", models.SmallIntegerField()),
                ("pass_cmp_perc", models.FloatField()),
                ("pass_yds", models.SmallIntegerField()),
                ("pass_td", models.SmallIntegerField()),
                ("pass_td_perc", models.FloatField()),
                ("pass_int", models.SmallIntegerField()),
                ("pass_int_perc", models.FloatField()),
                ("pass_first_down", models.SmallIntegerField()),
                ("pass_long", models.SmallIntegerField()),
                ("pass_yds_per_att", models.FloatField()),
                ("pass_adj_yds_per_att", models.FloatField()),
                ("pass_yds_per_cmp", models.FloatField()),
                ("pass_yds_per_g", models.FloatField()),
                ("pass_rating", models.FloatField()),
                ("qbr", models.FloatField()),
                ("pass_sacked", models.SmallIntegerField()),
                ("pass_sacked_yds", models.SmallIntegerField()),
                ("pass_sacked_perc", models.FloatField()),
                ("pass_net_yds_per_att", models.FloatField()),
                ("pass_adj_net_yds_per_att", models.FloatField()),
                ("comebacks", models.SmallIntegerField()),
                ("gwd", models.SmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_passing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerKicking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("age", models.SmallIntegerField()),
                ("pos", models.CharField(default=None, max_length=16)),
                ("g", models.SmallIntegerField()),
                ("gs", models.SmallIntegerField()),
                ("fga1", models.SmallIntegerField()),
                ("fgm1", models.SmallIntegerField()),
                ("fga2", models.SmallIntegerField()),
                ("fgm2", models.SmallIntegerField()),
                ("fga3", models.SmallIntegerField()),
                ("fgm3", models.SmallIntegerField()),
                ("fga4", models.SmallIntegerField()),
                ("fgm4", models.SmallIntegerField()),
                ("fga5", models.SmallIntegerField()),
                ("fgm5", models.SmallIntegerField()),
                ("fga", models.SmallIntegerField()),
                ("fgm", models.SmallIntegerField()),
                ("fg_long", models.SmallIntegerField()),
                ("fg_perc", models.FloatField()),
                ("xpa", models.SmallIntegerField()),
                ("xpm", models.SmallIntegerField()),
                ("xp_perc", models.FloatField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_kicking",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="football.team"
            ),
        ),
        migrations.CreateModel(
            name="DepthChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roster_spot", models.SmallIntegerField()),
                ("string", models.SmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.position",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.team",
                    ),
                ),
            ],
            options={
                "db_table": "depth_chart",
                "managed": True,
            },
        ),
    ]
