# Generated by Django 4.1.5 on 2023-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fbr_slug",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
