# Generated by Django 4.1.5 on 2023-08-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_player_fbr_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "conference",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("initials", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "league",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.conference",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.league",
                    ),
                ),
            ],
            options={
                "db_table": "division",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="conference",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="football.league"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.conference",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.division",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.league",
            ),
            preserve_default=False,
        ),
    ]
