# Generated by Django 4.1.5 on 2023-08-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0003_conference_league_division_conference_league_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="initials",
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
