# Generated by Django 4.1.5 on 2023-08-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0004_conference_initials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerpassing",
            name="pos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="football.position"
            ),
        ),
    ]
