# Generated by Django 4.1.5 on 2023-08-14 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0007_alter_teamoffense_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamoffense",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
            preserve_default=False,
        ),
    ]
