# Generated by Django 4.1.5 on 2023-08-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0008_alter_teamoffense_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerkicking",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
        ),
        migrations.AlterField(
            model_name="playerpassing",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
        ),
        migrations.AlterField(
            model_name="playerreceiving",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
        ),
        migrations.AlterField(
            model_name="playerreturning",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
        ),
        migrations.AlterField(
            model_name="playerrushing",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.team",
            ),
        ),
    ]
