# Generated by Django 4.1.5 on 2023-08-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0009_alter_playerkicking_team_alter_playerpassing_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerpassing",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.position",
            ),
        ),
    ]
