# Generated by Django 4.1.5 on 2023-08-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0010_alter_playerpassing_pos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerkicking",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.position",
            ),
        ),
        migrations.AlterField(
            model_name="playerreceiving",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.position",
            ),
        ),
        migrations.AlterField(
            model_name="playerreturning",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.position",
            ),
        ),
        migrations.AlterField(
            model_name="playerrushing",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.position",
            ),
        ),
    ]
