# Generated by Django 4.1.5 on 2023-08-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0011_alter_playerkicking_pos_alter_playerreceiving_pos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="espn_slug",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
