# Generated by Django 4.1.5 on 2023-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0012_team_espn_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="espn_id",
            field=models.SmallIntegerField(null=True),
        ),
    ]
