# Generated by Django 4.1.5 on 2023-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0013_player_espn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="espn_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
