# Generated by Django 4.1.5 on 2023-08-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0015_injurystatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="injurystatus",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="injurystatus",
            table="injury_status",
        ),
    ]
