# Generated by Django 4.1.5 on 2023-08-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0017_playerscrimmagebyteam_playerpassingbyteam"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProjections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proj_carries", models.FloatField(null=True)),
                ("proj_rush_yd", models.FloatField(null=True)),
                ("proj_rush_td", models.FloatField(null=True)),
                ("proj_tgt", models.FloatField(null=True)),
                ("proj_rec", models.FloatField(null=True)),
                ("proj_rec_yd", models.FloatField(null=True)),
                ("proj_rec_td", models.FloatField(null=True)),
                ("proj_points", models.FloatField(null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.player",
                    ),
                ),
            ],
            options={
                "db_table": "player_projection",
                "managed": True,
            },
        ),
    ]
