# Generated by Django 4.1.5 on 2024-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0020_defensivepoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnacleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "pinnacle_data",
                "managed": True,
            },
        ),
    ]
