# Generated by Django 4.1.5 on 2024-08-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0022_playerfbr_teamfbr_gamestats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerfbr",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="teamfbr",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="playerfbr",
            table="player_fbr",
        ),
        migrations.AlterModelTable(
            name="teamfbr",
            table="team_fbr",
        ),
    ]
