# Generated by Django 4.1.5 on 2024-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0022_gamefbr_playerfbr_teamfbr_gamestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamfbr",
            name="espn_depth_chart",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teamfbr",
            name="fbr_slug",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
