# Generated by Django 4.1.5 on 2024-08-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0023_alter_playerfbr_options_alter_teamfbr_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamestats",
            old_name="rushing_touchdowns",
            new_name="rushing_tds",
        ),
    ]
