# Generated by Django 4.1.5 on 2024-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0023_teamfbr_espn_depth_chart_teamfbr_fbr_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerfbr",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerfbr",
            name="position",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
