# Generated by Django 4.1.5 on 2024-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0024_rename_rushing_touchdowns_gamestats_rushing_tds"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestats",
            name="dt",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamestats",
            name="id",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
