# Generated by Django 4.1.5 on 2024-08-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0024_playerfbr_age_playerfbr_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerfbr",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.teamfbr",
            ),
        ),
    ]
